import { AnimatePresence, motion } from "framer-motion";
import { FiUserCheck, FiClock } from "react-icons/fi";
import SectionHeader from "../components/SectionHeader";

export default function RecruiterSummary({ data, collapsed, toggle }) {

    const summary = data.recruiterSummary || "";

    const words = summary.trim().split(/\s+/).length;

    const readTime = Math.max(1, Math.ceil(words / 180));

    return (

        <div>

            <SectionHeader
                icon={FiUserCheck}
                title="Recruiter Summary"
                subtitle="What an experienced recruiter would conclude"
                collapsed={collapsed}
                toggle={toggle}
                copyText={summary}
            />

            <AnimatePresence>

                {!collapsed && (

                    <motion.div
                        initial={{
                            opacity: 0,
                            height: 0
                        }}
                        animate={{
                            opacity: 1,
                            height: "auto"
                        }}
                        exit={{
                            opacity: 0,
                            height: 0
                        }}
                        transition={{
                            duration: .35
                        }}
                        className="overflow-hidden"
                    >

                        <div className="rounded-3xl border border-cyan-400/15 bg-linear-to-br from-cyan-500/8 via-white/2 to-violet-500/5 p-6">

                            <div className="flex flex-wrap items-center justify-between gap-4">

                                <div className="flex items-center gap-4">

                                    <div className="flex h-16 w-16 items-center justify-center rounded-2xl border border-cyan-400/20 bg-cyan-400/10">

                                        <FiUserCheck className="h-8 w-8 text-cyan-300" />

                                    </div>

                                    <div>

                                        <h3 className="text-xl font-bold text-white">

                                            AI Recruiter Opinion

                                        </h3>

                                        <p className="mt-1 text-sm text-slate-400">

                                            Generated from your resume and job description

                                        </p>

                                    </div>

                                </div>

                                <div className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/4 px-4 py-2">

                                    <FiClock className="text-cyan-300" />

                                    <span className="text-sm text-slate-300">

                                        {readTime} min read

                                    </span>

                                </div>

                            </div>

                            <div className="mt-8 rounded-2xl border border-white/10 bg-white/3 p-6">

                                <div className="mb-5 flex items-center gap-3">

                                    <div className="h-2 w-2 rounded-full bg-cyan-400" />

                                    <span className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan-300">

                                        Recruiter Perspective

                                    </span>

                                </div>

                                <p className="whitespace-pre-line text-[16px] leading-8 text-slate-300">

                                    {summary}

                                </p>

                            </div>

                            <div className="mt-8 grid gap-4 md:grid-cols-3">

                                <InsightCard
                                    title="Summary Length"
                                    value={`${words} Words`}
                                />

                                <InsightCard
                                    title="Estimated Reading"
                                    value={`${readTime} Minute`}
                                />

                                <InsightCard
                                    title="Generated By"
                                    value={data.generatedWith}
                                />

                            </div>

                        </div>

                    </motion.div>

                )}

            </AnimatePresence>

        </div>

    );

}

function InsightCard({
    title,
    value
}) {

    return (

        <div className="rounded-2xl border border-white/10 bg-white/3 p-5 transition-all duration-300 hover:border-cyan-400/30 hover:-translate-y-1">

            <p className="text-sm text-slate-400">

                {title}

            </p>

            <h4 className="mt-3 text-xl font-bold text-white wrap-break-word">

                {value}

            </h4>

        </div>

    );

}